# Generated by Django 2.2.13 on 2020-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='fabiano', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='ribeiro', max_length=200, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
    ]
